Repository EngStrategy/MundoAnimal, pull requests merged in 2025-02, with the labels that each got.

#29 pagination feature
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/AgendamentoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/AnimalController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/ClienteController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/SecretarioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/ServicoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/modals/ModalCriarSecretarioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/model/Cliente.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/model/Secretario.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/AnimalRepository.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/ServicoRepository.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/css/style.css
  src/main/resources/fxml/gerenciamento/agendamentos.fxml
  src/main/resources/fxml/gerenciamento/clientes.fxml
  src/main/resources/fxml/gerenciamento/pets.fxml
  src/main/resources/fxml/gerenciamento/secretarios.fxml
  src/main/resources/fxml/gerenciamento/servicos.fxml
Labels: feature

#32 home page
  src/main/java/com/carvalhotechsolutions/mundoanimal/Main.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/autenticacao/LoginController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/AgendamentoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/InicioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/MenuController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/enums/ScreenEnum.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/model/Agendamento.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/AgendamentoRepository.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/utils/ScreenManager.java
  src/main/resources/css/style.css
  src/main/resources/fxml/gerenciamento/clientes.fxml
  src/main/resources/fxml/gerenciamento/inicio.fxml
Labels: feature

#33 Feature/relatorio
  pom.xml
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/MenuController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/RelatorioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/enums/ScreenEnum.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/AgendamentoRepository.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/utils/AlertManager.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/utils/ModalManager.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/utils/RelatorioManager.java
  src/main/java/module-info.java
  src/main/resources/css/style.css
  src/main/resources/fxml/gerenciamento/relatorio.fxml
  src/main/resources/fxml/popup/genericAlert.fxml
Labels: feature

#35 Feature/details
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/AgendamentoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/ClienteController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/InicioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/RelatorioController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/gerenciamento/ServicoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/modals/ModalCriarAgendamentoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/modals/ModalCriarServicoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/controllers/modals/ModalDetalhesAgendamentoController.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/AgendamentoRepository.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/repositories/AnimalRepository.java
  src/main/java/com/carvalhotechsolutions/mundoanimal/utils/RelatorioManager.java
  src/main/resources/assets/images/confirmacao-login.png
  src/main/resources/css/style.css
  src/main/resources/fxml/gerenciamento/inicio.fxml
  src/main/resources/fxml/modals/modalDetalhesAgendamento.fxml
Labels: enhancement

#36 Conexão com o banco de dados da AWS
  pom.xml
  src/main/java/com/carvalhotechsolutions/mundoanimal/Main.java
  src/main/java/module-info.java
Labels: dependencies
